export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const FEATURE_LOADED = 'FEATURE_LOADED';
export const MATCHCARD_LOADED = 'MATCHCARD_LOADED';
export const MATCH_CREATED = 'MATCH_CREATED';
export const MATCH_DELETED = 'MATCH_DELETED';
